services:
  api:
    build: ./api
    container_name: ${COMPOSE_PROJECT_NAME:-jsonify2ai-main}-api-1
    ports:
      - "${PORT_API:-8082}:8082"
    volumes:
      - ./data:/app/data
    env_file:
      - ./.env
    environment:
      - PORT_API=${PORT_API:-8082}
      - DOCS_DIR=/app/data/documents
      - GIN_MODE=${GIN_MODE:-release}
      - GIN_TRUSTED_PROXIES=${GIN_TRUSTED_PROXIES:-}
    restart: unless-stopped
  worker:
    build: ./worker
    image: jsonify2ai-worker:latest
    ports: ["8090:8090"]
    volumes:
      - ./data:/app/data
    environment:
      QDRANT_URL: "http://host.docker.internal:6333"
      OLLAMA_URL: "http://host.docker.internal:11434"
      EMBED_DEV_MODE: ${EMBED_DEV_MODE:-0}
      IMAGES_CAPTION: ${IMAGES_CAPTION:-0}
      ASK_MODE: ${ASK_MODE}
      ASK_MODEL: ${ASK_MODEL}
    healthcheck:
      test: ["CMD","curl","-fsS","http://localhost:8090/health"]
      interval: 10s
      timeout: 3s
      retries: 10

networks:
  default:
    driver: bridge
