
services:
  api:
    build: ./api
    ports:
      - "${PORT_API:-8082}:8082"
    environment:
      - POSTGRES_DSN=${POSTGRES_DSN}
      - QDRANT_URL=${QDRANT_URL}
      - OLLAMA_URL=${OLLAMA_URL}
      - WORKER_BASE=${WORKER_BASE:-http://worker:8090}
    networks:
      - default

  worker:
    build: ./worker
    ports:
      - "${PORT_WORKER:-8090}:8090"
    environment:
      - POSTGRES_DSN=${POSTGRES_DSN}
      - QDRANT_URL=${QDRANT_URL}
      - OLLAMA_URL=${OLLAMA_URL:-http://host.docker.internal:11434}
      - EMBED_DEV_MODE=${EMBED_DEV_MODE:-0}
      - EMBEDDING_DIM=${EMBEDDING_DIM:-768}
      - DEBUG_CONFIG=${DEBUG_CONFIG:-0}
      - PORT_WORKER=${PORT_WORKER:-8090}
    networks:
      - default

  web:
    build: ./web
    ports:
      - "${PORT_WEB:-5173}:5173"
    environment:
      - PORT_WEB=${PORT_WEB:-5173}
    networks:
      - default

networks:
  default:
    driver: bridge
